### ISSUE TITLE
TrinityCore 2016_06 Creator Profile

### ISSUE THREAD

**Issue by Variona** [NotCoffee418/TrinityCreator#84]
[TrinityCore_2016_06_26 .txt](https://github.com/NotCoffee418/TrinityCreator/files/4131438/TrinityCore_2016_06_26.txt)

Can't upload .json files so I changed it to a .txt

**Comment by illfated** [comment]
Oh. I see. https://github.com/conan513/SingleCore_TC / https://github.com/conan513/SingleCore_TC/commit/a596478095d542b14089a49b559adeeb853808a1
That explains the DBC dates from 2016.

**Comment by NotCoffee418** [comment]
@Variona Very nice! Thanks for contributing. :D
I'll add it to the list!

@illfated Yeah but DBC files don't change (as far as i know?) unless it's between game versions.

**Comment by NotCoffee418** [comment]
EDIT: This isn't documented yet (working on it) but your profile won't work beyond items right now because you don't have any custom fields but you do have addon templates listed.

Basically you need to manually define the ID for quest_template_addon, quest_offer_reward, quest_offer_reward, creature_questender, creature_equip_template, creature_classlevelstats, creature_template_addon

Otherwise it'll attempt to put for example:
INSERT INTO creature_equip_template (ItemID1, ItemID2, ItemID3) VALUES ...
But it won't reference to the creature's ID.

You can define these at the bottom in custom fields like so:
![image](https://user-images.githubusercontent.com/9306304/73410871-d4a88c00-4303-11ea-8dcc-2433ae59bc5d.png)


First field being what it references (in all of these it's the entry ID so one of these (and keep in mind these are case sensitive)
- Quest.EntryId
- Creature.Entry
- Item.EntryID

Second field being the name of the id column in the table you're trying to support. (so the ID column name of for creature_template_addon)

And the third field being the table name (creature_template_addon in this example)

I can't complete it myself since i'm not in the mood to set up a build of an unknown emulator right about now :P

**Comment by Variona** [comment]
Yeah, my quest creator doesn't work. I'll look into it more tomorrow. But my creature one works now. Cheers.

**Comment by Variona** [comment]
Just realized I never updated this. This one works.

[Variona TC 2016.txt](https://github.com/NotCoffee418/TrinityCreator/files/4462298/Variona.TC.2016.txt)

**Comment by NotCoffee418** [comment]
I'll trust it works and add it. ^^
Thanks for your contribution!
